# Generated by Django 4.2.5 on 2023-09-14 21:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, help_text='Updated at', verbose_name='updated_at'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, help_text='Is active?', verbose_name='is_active'
                    ),
                ),
                ('name', models.TextField(help_text="Lab's name", verbose_name='name')),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, help_text='Updated at', verbose_name='updated_at'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, help_text='Is active?', verbose_name='is_active'
                    ),
                ),
                (
                    'started_at',
                    models.DateTimeField(
                        help_text='Test started at', verbose_name='started_at'
                    ),
                ),
                (
                    'completed_at',
                    models.DateTimeField(
                        help_text='Test completed at', verbose_name='completed_at'
                    ),
                ),
                (
                    'comment',
                    models.TextField(help_text="Test's comment", verbose_name='comment'),
                ),
                (
                    'lab_id',
                    models.ForeignKey(
                        help_text="Lab's id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tests',
                        to='labs.lab',
                        verbose_name='lab_id',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, help_text='Updated at', verbose_name='updated_at'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, help_text='Is active?', verbose_name='is_active'
                    ),
                ),
                ('score', models.IntegerField(help_text='Score', verbose_name='score')),
                (
                    'indicator_metric_id',
                    models.ForeignKey(
                        help_text='IndicatorMetric id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scores',
                        to='indicators.indicatormetric',
                        verbose_name='indicator_metric_id',
                    ),
                ),
                (
                    'test_id',
                    models.ForeignKey(
                        help_text='Test id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scores',
                        to='labs.test',
                        verbose_name='test_id',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ('-created_at',),
            },
        ),
    ]
