# Generated by Django 4.2.5 on 2023-09-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(
                decimal_places=10, help_text='Score', max_digits=20, verbose_name='score'
            ),
        ),
    ]
