# Generated by Django 4.2.5 on 2023-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('labs', '0002_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.TextField(
                help_text="Lab's name", unique=True, verbose_name='name'
            ),
        ),
    ]
