# Generated by Django 4.2.5 on 2023-09-14 21:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, help_text='Updated at', verbose_name='updated_at'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, help_text='Is active?', verbose_name='is_active'
                    ),
                ),
                (
                    'name',
                    models.TextField(help_text="Indicator's name", verbose_name='name'),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Indicator description', verbose_name='description'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IndicatorMetric',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, help_text='Updated at', verbose_name='updated_at'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, help_text='Is active?', verbose_name='is_active'
                    ),
                ),
                (
                    'indicator_id',
                    models.ForeignKey(
                        help_text='Indicator id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='indicator_metrics',
                        to='indicators.indicator',
                        verbose_name='indicator_id',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Indicator Metric',
                'verbose_name_plural': 'Indicator Metrics',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, help_text='Updated at', verbose_name='updated_at'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, help_text='Is active?', verbose_name='is_active'
                    ),
                ),
                (
                    'name',
                    models.TextField(help_text="Indicator's name", verbose_name='name'),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Indicator description', verbose_name='description'
                    ),
                ),
                (
                    'unit',
                    models.TextField(help_text="Metric's unit", verbose_name='unit'),
                ),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, help_text='Updated at', verbose_name='updated_at'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, help_text='Is active?', verbose_name='is_active'
                    ),
                ),
                (
                    'min_score',
                    models.PositiveSmallIntegerField(
                        help_text='Min score', verbose_name='min_score'
                    ),
                ),
                (
                    'max_score',
                    models.PositiveSmallIntegerField(
                        help_text='Max score', verbose_name='max_score'
                    ),
                ),
                (
                    'indicator_metric_id',
                    models.ForeignKey(
                        help_text='IndicatorMetric id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='references',
                        to='indicators.indicatormetric',
                        verbose_name='indicator_metric_id',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='indicatormetric',
            name='metric_id',
            field=models.ForeignKey(
                help_text='Metric id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='indicator_metrics',
                to='indicators.metric',
                verbose_name='metric_id',
            ),
        ),
    ]
