# Generated by Django 4.2.5 on 2023-09-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='max_score',
            field=models.DecimalField(
                decimal_places=10,
                help_text='Max score',
                max_digits=20,
                verbose_name='max_score',
            ),
        ),
        migrations.AlterField(
            model_name='reference',
            name='min_score',
            field=models.DecimalField(
                decimal_places=10,
                help_text='Min score',
                max_digits=20,
                verbose_name='min_score',
            ),
        ),
    ]
