version: '3.3'

services:

  postgres:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - labs_postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  labs_postgres_volume:
