version: '3.3'

services:

  postgres:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - labs_postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: ../../
    restart: always
    depends_on:
      - postgres
    env_file:
      - ../../lab_project/lab_project/.env
    volumes:
      - labs_static_volume:/app/lab_project/static/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - labs_static_volume:/var/html/static/
    depends_on:
      - web

volumes:
  labs_postgres_volume:
  labs_static_volume:
