name: Lab System backend

on: [push]

jobs:

  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        linter: ["flake8", "mypy"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/dev.txt

    - name: Test with ${{ matrix.linter }}
      run: ${{ matrix.linter }} .

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      DJANGO_SECRET_KEY: super_secret_key

    services:

      postgres:
        image: postgres:15.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/tests.txt

    - name: Test with pytest
      working-directory: ./lab_project
      run: |
        pytest ..
